baseURL = "https://kleinen-Strolche-Oberhohndorf.github.io"
languageCode = "de-DE"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "FÃ¶rderverein der Kita Oberhohndorf"
paginate = 5
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = ""
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#01545B'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#01545B"
  enableGoogleFonts = false
  #googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Helvetica"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    name = "Spenden"
    identifier = "spenden"
    weight = 1
    url = "/spenden/"
  [[menu.main]]
    name = "Mitgliedsantrag"
    identifier = "mitgliedsantrag"
    weight = 2
    url = "/mitgliedsantrag/"
  [[menu.main]]
    name = "Impressum"
    identifier = "impressum"
    weight = 3
    url = "/impressum/"
  [[menu.main]]
    name = "Datenschutz"
    identifier = "datenschutz"
    weight = 4
    url = "/datenschutz/"
